from pathlib import Path
p = Path('src/routes/jogar/+page.svelte')
t = p.read_text(encoding='utf-8')
old = "\t\t\t\t<table class=\\\"mapa-grid\\\">\n\t\t\t\t\t{#each mapa as linha, r}\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t{#each linha as celula, c}\n\t\t\t\t\t\t\t\t{#if celula === 'obstacle'}\n\t\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t\t⬛\n\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t{:else if playerPosition.r === r && playerPosition.c === c}\n\t\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula + ' player'} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t\t{personagemAtivo?.emoji ?? '👤'}\n\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t{:else}\n\t\t\t\t\t\t\t\t\t{#if caminho.length}\n\t\t\t\t\t\t\t\t\t\t{#if caminho.findIndex(p => p.r === r && p.c === c) >= 0 && caminho.findIndex(p => p.r === r && p.c === c) <= destaqueIndex}\n\t\t\t\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula + ' highlight'} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t\t\t\t{#if celula === 'start'}\n\t\t\t\t\t\t\t\t\t\t\t\t\t🏁\n\t\t\t\t\t\t\t\t\t\t\t\t{:else if celula === 'goal'}\n\t\t\t\t\t\t\t\t\t\t\t\t\t🎯\n\t\t\t\t\t\t\t\t\t\t\t\t{:else if celula === 'challenge'}\n\t\t\t\t\t\t\t\t\t\t\t\t\t❗\n\t\t\t\t\t\t\t\t\t\t\t\t{:else}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t\t{:else}\n\t\t\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t\t\t{#if celula === 'start'}\n\t\t\t\t\t\t\t\t\t\t\t\t🏁\n\t\t\t\t\t\t\t\t\t\t\t\t{:else if celula === 'goal'}\n\t\t\t\t\t\t\t\t\t\t\t\t🎯\n\t\t\t\t\t\t\t\t\t\t\t\t{:else if celula === 'challenge'}\n\t\t\t\t\t\t\t\t\t\t\t\t❗\n\t\t\t\t\t\t\t\t\t\t\t\t{:else}\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t{/each}\n\t\t\t\t\t</tr>\n\t\t\t\t{/each}\n'
new = "\t\t\t\t<table class=\\\"mapa-grid\\\">\n\t\t\t\t\t{#each mapa as linha, r}\n\t\t\t\t\t\t<tr>\n\t\t\t\t\t\t\t{#each linha as celula, c}\n\t\t\t\t\t\t\t\t{#if playerPosition.r === r && playerPosition.c === c}\n\t\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula + ' player'} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t\t{personagemAtivo?.emoji ?? '👤'}\n\t\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t\t{:else}\n\t\t\t\t\t\t\t\t<td class={\\\"celula tile \\\" + celula + (destaqueNoCaminho(r, c) ? ' highlight' : '')} style={estiloTile(celula, r, c)}>\n\t\t\t\t\t\t\t\t\t{#if celula === 'start'}\n\t\t\t\t\t\t\t\t\t\t🏁\n\t\t\t\t\t\t\t\t\t{:else if celula === 'goal'}\n\t\t\t\t\t\t\t\t\t\t🎯\n\t\t\t\t\t\t\t\t\t{:else if celula === 'challenge'}\n\t\t\t\t\t\t\t\t\t\t❗\n\t\t\t\t\t\t\t\t\t{:else if celula === 'battle'}\n\t\t\t\t\t\t\t\t\t\t⚔️\n\t\t\t\t\t\t\t\t\t{:else if celula === 'locked'}\n\t\t\t\t\t\t\t\t\t\t🔒\n\t\t\t\t\t\t\t\t\t{:else if celula === 'obstacle'}\n\t\t\t\t\t\t\t\t\t\t⬛\n\t\t\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t\t</td>\n\t\t\t\t\t\t{/if}\n\t\t\t\t\t\t{/each}\n\t\t\t\t\t</tr>\n\t\t\t\t{/each}\n"
if old not in t:
    raise SystemExit('old block not found')
t = t.replace(old, new)
p.write_text(t, encoding='utf-8')
